// packages/library-pipeline/src/textbook/educational-validation-v2.test.ts
// All persons, ratings, dates and scores are synthetic regression fixtures, never human-study data.
import {describe,it,expect} from 'vitest'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {execFileSync} from 'node:child_process'
import {createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
import {SEMANTIC_CRITERIA} from './educational-validation'
import {bundleV2Schema,refreshV2Hashes,digestV2,manifestIdentityV2,registerV2,evaluateV2,expertOutcomeV2,studentBindingV2,productionV2,calibrationCompletedV2,deliveryPacketV2,type BundleV2} from './educational-validation-v2'
import {emptyResponseV2,mergeResponsesV2} from './educational-responses-v2'
import {researchBodyHash} from '../ingest-article/research-origin'
import {validateEducationalPromotion,assertIndependentOfFixedCalibration} from '../../../../scripts/textbook/educational-validation-contract.mjs'
const now=Date.parse('2026-10-05T00:00:00Z'),text='Synthetic researchers observed a relationship in a limited sample. Association does not establish a cause.'
const H='a'.repeat(64),approved='2026-10-02T00:00:00Z',reviewed='2026-10-03T00:00:00Z',started='2026-10-04T00:00:00Z',finished='2026-10-04T00:02:00Z'
function seal(b:BundleV2){refreshV2Hashes(b);b.protocol_approval={human_lead_id:'lead-test',approved_at:approved,manifest_hash:digestV2(manifestIdentityV2(b)),registration_evidence:'Synthetic registration receipt for regression only.'};for(const r of b.records){for(const e of r.expert_reviews)e.packet_hash=deliveryPacketV2(b,r,'expert').packet_hash;for(const s of r.student_sessions)s.packet_hash=deliveryPacketV2(b,r,'student').packet_hash}return b}
function fixture(purpose:'calibration'|'validation'|'replication'='validation'){
 const experts=['expert-one','expert-two','expert-third'].map(id=>({id,kind:'human_domain_expert',independent_of_author:true,credential_verified_by:'lead-test',qualification_evidence:'Synthetic qualification for regression only.',screened_at:'2026-10-01T00:00:00Z',screened_by:'lead-test',prior_exposure:[],blind_eligible:true,screening_evidence:'Synthetic independent exposure screening only.'}))
 const records=['middle_1','high_1'].map((grade,index)=>{
  const r={id:`record-${grade}`,pair_id:'pair-synthetic',blind_item_id:`B-${grade}`,source_id:'11111111-1111-4111-8111-111111111111',source_hash:H,source_revision:'synthetic-1',research_hash:H,target_key:String(index+1).repeat(24),grade,passage_hash:researchBodyHash(text),link_confidence:'high',provenance_verified:true,research_doi:'10.9999/test',research_contexts:[text],adapted_passage:text,topic:'synthetic-topic',source_family:'synthetic-source',expert_assignment:{initial_expert_ids:['expert-one','expert-two'],adjudicator_id:'expert-third'},adjudication:null,
   instrument:['comprehension','lexical','syntax','reasoning'].flatMap(axis=>[1,2,3].map(n=>({id:`${axis}-${n}`,axis,prompt:'Explain this synthetic sentence.',source_quote:text,scoring_rubric:'Retain association without asserting causality.'}))),expert_reviews:[] as unknown[],student_sessions:[] as unknown[]}
  r.expert_reviews=['expert-one','expert-two'].map(expert_id=>({expert_id,blind_item_id:r.blind_item_id,passage_hash:r.passage_hash,packet_hash:H,rated_at:reviewed,ratings:Object.fromEntries(SEMANTIC_CRITERIA.map(k=>[k,{score:4,critical:false,passage_quote:text,research_quote:text,reason:'Synthetic faithful comparison for regression only.'}])),distortions:[],reason:'Synthetic independently passing review for testing.'}))
  r.student_sessions=Array.from({length:15},(_,n)=>({student_id:`student-${grade}-${n}`,grade,packet_hash:H,grade_verified_by:'lead-test',reading_started_at:started,reading_finished_at:finished,unknown_word_count:0,lexical_burden:2,sentence_burden:2,reasoning_burden:2,perceived_difficulty:2,answers:r.instrument.map(i=>({item_id:i.id,response:'Synthetic answer preserving the meaning.',score:1,scorer_id:'expert-one'}))}))
  return r
 })
 const b=bundleV2Schema.parse({version:2,mode:'local_educational_validation',taxonomy_version:1,study_id:'study-test',pilot_hash:H,review_hash:H,rules_hash:H,protocol_hash:H,instrument_hash:H,protocol:{version:2,description:'Synthetic preregistered design for regression only.',study_purpose:purpose,scale_points:4,score_anchors:Array(4).fill('Synthetic anchor for regression testing only.'),minimum_item_score:3,minimum_experts:2,minimum_students_per_variant:15,minimum_students_per_grade:15,minimum_items_per_axis:3,ranges:['middle_1','high_1'].map(grade=>({grade,reading_seconds:{min:60,max:180},comprehension_accuracy:{min:.8,max:1},lexical_accuracy:{min:.8,max:1},syntax_accuracy:{min:.8,max:1},reasoning_accuracy:{min:.8,max:1},unknown_word_fraction:{min:0,max:.1},lexical_burden:{min:1,max:3},sentence_burden:{min:1,max:3},reasoning_burden:{min:1,max:3},perceived_difficulty:{min:1,max:3}})),band_rationale:{middle_1:'Synthetic middle grade rationale for testing.',high_1:'Synthetic high grade rationale for testing.'},operations:'Synthetic session and missingness plan only.',expert_reuse_allowed:false,failed_passage_policy:'skip_only_after_completed_failure'},experts,participants:records.flatMap(r=>r.student_sessions.map((s:any)=>({student_id:s.student_id,grade:r.grade,grade_verified_by:'lead-test',record_order:[r.id]}))),calibration_exclusions:purpose==='calibration'?[]:[{study_id:'earlier-calibration',file_hash:H,manifest_hash:H,completed_at:'2026-10-01T00:00:00Z',source_ids:['22222222-2222-4222-8222-222222222222'],research_dois:['10.9999/earlier'],passage_hashes:['b'.repeat(64)],student_ids:['earlier-student'],expert_ids:['earlier-expert'],evidence:'Synthetic calibration exclusion manifest for testing.'}],protocol_approval:null,records})
 return seal(b)
}
const passages=(b:BundleV2)=>Object.fromEntries(b.records.map(r=>[r.id,text]))
function adjudicate(b:BundleV2){const r=b.records[0]!,third={...structuredClone(r.expert_reviews[0]!),expert_id:'expert-third',rated_at:'2026-10-03T01:00:00Z'};r.expert_reviews.push(third);r.adjudication={adjudicator_id:'expert-third',initial_review_hashes:r.expert_reviews.slice(0,2).map(digestV2),adjudicator_independent_review_hash:digestV2(third),initial_reviews_disclosed_at:'2026-10-03T02:00:00Z',adjudicated_at:'2026-10-03T03:00:00Z',item_resolution:structuredClone(third.ratings),final_distortions:[],unresolved_items:[],evidence_and_reason:'Synthetic resolved disagreement with preserved originals.'}}
describe('human validation v2 gates',()=>{
 it('requires every registered gate and separates calibration from gold',()=>{const b=fixture(),r=b.records[0]!;expect(evaluateV2(b,r,text,now)).toMatchObject({state:'gold',blockers:[],student_count:15,production:false});const c=fixture('calibration');expect(evaluateV2(c,c.records[0]!,text,now).state).toBe('student_validated')})
 it('new seed certificate binds v2 gold, final adjudication dimensions and exact passage/target',()=>{const b=fixture(),r=b.records[0]!,task={review_hash:b.review_hash,rules_hash:b.rules_hash,entry:{source_id:r.source_id,source_hash:r.source_hash,source_revision:r.source_revision,research_hash:r.research_hash,pair_id:r.pair_id}},draft={text,reading:{target_key:r.target_key,target:{age_band:r.grade}}},validation={bundle:b,file_hash:H,provenance:{[r.id]:{verified:true,confidence:'high'}}};expect(validateEducationalPromotion(draft,task,validation,now)).toMatchObject({ok:true,certificate:{version:2,state:'gold',manifest_hash:b.protocol_approval!.manifest_hash,final_semantic_dimensions:{claim_preserved:true}}});expect(validateEducationalPromotion({...draft,text:text+' Changed.'},task,validation,now).ok).toBe(false);r.expert_reviews[0]!.ratings.core_claim.critical=true;expect(validateEducationalPromotion(draft,task,validation,now).ok).toBe(false)})
 it('all real draft fields stay unsealed and metrics null',()=>{const b=fixture('calibration');b.protocol_approval=null;b.experts=[];b.participants=[];for(const r of b.records){r.expert_reviews=[];r.student_sessions=[];r.expert_assignment=null}const x=evaluateV2(b,b.records[0]!,text,now);expect(x.state).toBe('candidate');expect(Object.values(x.metrics).every(v=>v===null)).toBe(true);expect(mergeResponsesV2(b,emptyResponseV2(b),passages(b),now).stats.added_student_sessions).toBe(0)})
 it.each(['core_claim','causal_direction','comparison_relation','conditions_and_scope','no_key_omission','no_epistemic_overstatement'] as const)('critical %s cannot be rescued by other high scores or adjudication',key=>{const b=fixture(),r=b.records[0]!;r.expert_reviews[0]!.ratings[key].critical=true;adjudicate(b);expect(evaluateV2(b,r,text,now).blockers).toContain('critical_rejection');expect(evaluateV2(b,r,text,now).state).toBe('candidate')})
 it.each(SEMANTIC_CRITERIA)('item minimum blocks %s even with high mean',key=>{const b=fixture(),r=b.records[0]!;for(const e of r.expert_reviews)e.ratings[key].score=2;expect(evaluateV2(b,r,text,now).blockers).toContain('semantic_review_not_passed')})
 it('disagreement requires independently bound third adjudication',()=>{const b=fixture(),r=b.records[0]!;r.expert_reviews[1]!.ratings.core_claim.score=3;expect(evaluateV2(b,r,text,now).blockers).toContain('independent_adjudication_required');adjudicate(b);expect(evaluateV2(b,r,text,now).state).toBe('gold');expect(r.expert_reviews[1]!.ratings.core_claim.score).toBe(3)})
 it.each(['early_disclosure','same_person','wrong_hash','unresolved','wrong_evidence','future_adjudication'])('blocks adjudication %s',kind=>{const b=fixture(),r=b.records[0]!;r.expert_reviews[1]!.ratings.core_claim.score=3;adjudicate(b);const a=r.adjudication!;if(kind==='early_disclosure')a.initial_reviews_disclosed_at=reviewed;if(kind==='same_person')a.adjudicator_id='expert-one';if(kind==='wrong_hash')a.initial_review_hashes[0]='c'.repeat(64);if(kind==='unresolved')a.unresolved_items=['core_claim'];if(kind==='wrong_evidence')a.item_resolution.core_claim.research_quote='Absent original research quote';if(kind==='future_adjudication')a.adjudicated_at='2026-10-06T00:00:00Z';expect(evaluateV2(b,r,text,now).blockers).toContain('independent_adjudication_required')})
 it.each(['passage','bands','participants','contexts','assignment','screening','rationale','exclusions'])('seal binds %s',kind=>{const b=fixture(),r=b.records[0]!;if(kind==='passage')r.passage_hash='f'.repeat(64);if(kind==='bands')b.protocol.ranges[0]!.reading_seconds=null;if(kind==='participants')b.participants.pop();if(kind==='contexts')r.research_contexts.push('Another research passage context.');if(kind==='assignment')r.expert_assignment!.adjudicator_id='expert-one';if(kind==='screening')b.experts[0]!.prior_exposure=['saw prior model results'];if(kind==='rationale')b.protocol.band_rationale.middle_1=null;if(kind==='exclusions')b.calibration_exclusions=[];expect(evaluateV2(b,r,text,now).state).toBe('candidate')})
 it.each(['source','doi','passage','student','expert'])('validation excludes calibration %s',kind=>{const b=fixture(),r=b.records[0]!,e=b.calibration_exclusions[0]!;if(kind==='source')e.source_ids=[r.source_id];if(kind==='doi')e.research_dois=[r.research_doi];if(kind==='passage')e.passage_hashes=[r.passage_hash];if(kind==='student')e.student_ids=[b.participants[0]!.student_id];if(kind==='expert')e.expert_ids=[b.experts[0]!.id];seal(b);expect(evaluateV2(b,r,text,now).blockers).toContain('calibration_validation_overlap')})
 it.each(['record','exclusion'])('calibration UUID overlap ignores uppercase %s spelling',kind=>{const b=fixture(),id='abcdefab-cdef-4abc-8def-abcdefabcdef';b.records[0]!.source_id=kind==='record'?id.toUpperCase():id;b.calibration_exclusions[0]!.source_ids=[kind==='exclusion'?id.toUpperCase():id];seal(b);expect(evaluateV2(b,b.records[0]!,text,now).blockers).toContain('calibration_validation_overlap')})
 it('partial records, missing answers and fourteen students never certify a variant',()=>{const b=fixture(),r=b.records[0]!;r.student_sessions[0]!.answers[0]!.score=null;expect(evaluateV2(b,r,text,now)).toMatchObject({state:'expert_validated',student_count:14,missing_sessions:1});r.student_sessions=[];expect(evaluateV2(b,r,text,now).metrics.lexical_accuracy).toBeNull()})
 it('unknown scorer, grade mismatch and premature reading are excluded',()=>{for(const kind of ['scorer','grade','early']){const b=fixture(),r=b.records[0]!,s=r.student_sessions[0]!;if(kind==='scorer')s.answers[0]!.scorer_id='unknown';if(kind==='grade')s.grade='high_1';if(kind==='early')s.reading_started_at=approved;expect(evaluateV2(b,r,text,now).student_count).toBe(14)}})
 it('human registration precedes responses and cannot fabricate a complete protocol',()=>{const b=fixture();b.protocol_approval=null;expect(()=>registerV2(b,{human_lead_id:'lead-test',approved_at:approved,manifest_hash:digestV2(manifestIdentityV2(b)),registration_evidence:'Synthetic receipt for tests only.'},now)).toThrow('precede');for(const r of b.records){r.expert_reviews=[];r.student_sessions=[]}b.protocol.ranges[0]!.lexical_accuracy=null;seal(b);const a=b.protocol_approval!;b.protocol_approval=null;expect(()=>registerV2(b,a,now)).toThrow('incomplete')})
 it('published status alone cannot produce production',()=>{const b=fixture(),r=b.records[0]!,article={status:'published',content:text,adapted_from_id:r.source_id,composed_spec:{academic_reading:{target_key:r.target_key}}};expect(productionV2(b,r,text,b,passages(b),article,now)).toBe(false);const p=fixture('replication');p.study_id='study-replication';seal(p);expect(productionV2(b,r,text,p,passages(p),article,now)).toBe(false)})
 it('rejects malformed dates and short external registration evidence before writing a seal',()=>{for(const bad of [{approved_at:'not-a-date'},{registration_evidence:'short'}]){const b=fixture(),a={...b.protocol_approval!,...bad};b.protocol_approval=null;for(const r of b.records){r.expert_reviews=[];r.student_sessions=[]}expect(()=>registerV2(b,a,now)).toThrow()}})
 it('noncritical distortion disagreement can be resolved without erasing originals',()=>{const b=fixture(),r=b.records[0]!;r.expert_reviews[0]!.distortions=[{code:'UNSUPPORTED_DETAIL',severity:'major',passage_quote:text,reason:'Synthetic suspected unsupported detail requiring adjudication.'}];adjudicate(b);expect(evaluateV2(b,r,text,now).state).toBe('gold');expect(r.expert_reviews[0]!.distortions).toHaveLength(1);r.adjudication!.final_distortions=structuredClone(r.expert_reviews[0]!.distortions);expect(evaluateV2(b,r,text,now).blockers).toContain('distortion_present')})
 it('reports accuracy n and IQR per student, with separate item counts',()=>{const b=fixture(),r=b.records[0]!,result=evaluateV2(b,r,text,now);expect(result.distributions.lexical_accuracy.n).toBe(15);expect(result.item_responses.find(i=>i.axis==='lexical')!.n).toBe(15);expect(result.order_positions[0]!.complete).toBe(15)})
 it('cannot skip an unresolved noncritical failed initial rating, but can skip final failure',()=>{
  const b=fixture(),prior=b.records[0]!,next=structuredClone(prior);next.id='record-next';next.pair_id='pair-next';next.blind_item_id='B-next';next.source_id='33333333-3333-4333-8333-333333333333';next.target_key='3'.repeat(24);next.student_sessions=[];for(const e of next.expert_reviews)e.blind_item_id=next.blind_item_id;b.records.push(next)
  const ps=b.participants.filter(p=>p.grade==='middle_1');for(const [index,p] of ps.entries())p.record_order=index<8?[prior.id,next.id]:[next.id,prior.id];prior.student_sessions=[];seal(b)
  const s={...structuredClone(fixture().records[0]!.student_sessions[0]!)}
  s.packet_hash=deliveryPacketV2(b,next,'student').packet_hash
  prior.expert_reviews[0]!.ratings.core_claim.score=2
  expect(studentBindingV2(b,next,s,text,now)).toBe(false)
  prior.expert_reviews[1]!.ratings.core_claim.score=2
  expect(studentBindingV2(b,next,s,text,now)).toBe(true)
 })
 it('requires balanced preregistered order, not ad hoc passage skipping',()=>{const b=fixture(),r=b.records[0]!,copy=structuredClone(r);copy.id='record-next';copy.pair_id='pair-next';copy.blind_item_id='B-next';copy.target_key='3'.repeat(24);copy.student_sessions=[];for(const e of copy.expert_reviews)e.blind_item_id=copy.blind_item_id;b.records.push(copy);for(const p of b.participants.filter(p=>p.grade==='middle_1'))p.record_order=[r.id,copy.id];seal(b);expect(evaluateV2(b,r,text,now).blockers).toContain('student_order_unbalanced_middle_1')})
 it('production requires later completed independent replication with different topic/source and exact published row',()=>{
  const b=fixture(),r=b.records[0]!,p=fixture('replication'),repText=text+' Another independent sample.',article={status:'published',content:text,adapted_from_id:r.source_id,composed_spec:{academic_reading:{target_key:r.target_key}}}
  p.study_id='later-replication';p.protocol.expert_reuse_allowed=true;for(const participant of p.participants)participant.student_id='rep-'+participant.student_id
  for(const x of p.records){x.topic='other-topic';x.source_family='other-source';x.source_id='44444444-4444-4444-8444-444444444444';x.research_doi='10.9999/other';x.adapted_passage=repText;x.passage_hash=researchBodyHash(repText);for(const e of x.expert_reviews){e.passage_hash=x.passage_hash;e.rated_at='2026-10-07T00:00:00Z'}for(const s of x.student_sessions){s.student_id='rep-'+s.student_id;s.reading_started_at='2026-10-08T00:00:00Z';s.reading_finished_at='2026-10-08T00:02:00Z'}}
  for(const e of p.experts)e.screened_at='2026-10-05T00:00:00Z';seal(p);p.protocol_approval={...p.protocol_approval!,approved_at:'2026-10-06T00:00:00Z',manifest_hash:digestV2(manifestIdentityV2(p))};const repPassages=Object.fromEntries(p.records.map(x=>[x.id,repText])),later=Date.parse('2026-10-09T00:00:00Z')
  expect(productionV2(b,r,text,p,repPassages,article,later)).toBe(true);const approvalTime=p.protocol_approval!.approved_at;p.protocol.expert_reuse_allowed=false;seal(p);p.protocol_approval!.approved_at=approvalTime;expect(evaluateV2(p,p.records[0]!,repText,later).state).toBe('gold');expect(productionV2(b,r,text,p,repPassages,article,later)).toBe(false);p.protocol.expert_reuse_allowed=true;seal(p);p.protocol_approval!.approved_at=approvalTime;expect(productionV2(b,r,text,p,repPassages,{...article,status:'queued'},later)).toBe(false);
  r.source_id='abcdefab-cdef-4abc-8def-abcdefabcdef';article.adapted_from_id=r.source_id;seal(b);p.records[0]!.source_id=r.source_id.toUpperCase();seal(p);p.protocol_approval!.approved_at=approvalTime;expect(evaluateV2(p,p.records[0]!,repText,later).state).toBe('gold');expect(productionV2(b,r,text,p,repPassages,article,later)).toBe(false);p.records[0]!.source_id='44444444-4444-4444-8444-444444444444';seal(p);p.protocol_approval!.approved_at=approvalTime;expect(productionV2(b,r,text,p,repPassages,article,later)).toBe(true);p.records[0]!.student_sessions.pop();expect(productionV2(b,r,text,p,repPassages,article,later)).toBe(false)
 })
})
describe('v2 response collection',()=>{
 it('retains pre-revision v2 English packets and responses without changing sealed identity',()=>{const b=bundleV2Schema.parse(fixture()),r=b.records[0]!,packet=deliveryPacketV2(b,r,'student');expect(b.protocol).not.toHaveProperty('student_instructions_revision');expect(packet.payload.instructions).toBe('Read first and record reading start/end before answering. Mark unknown word occurrences. Answer in Korean or English. Do not access scoring rubrics.');expect(packet.manifest_hash).toBe(b.protocol_approval!.manifest_hash);const batch=emptyResponseV2(b) as any;batch.student_sessions=[{...structuredClone(r.student_sessions[0]!),blind_item_id:r.blind_item_id,passage_hash:r.passage_hash}];r.student_sessions=[];expect(mergeResponsesV2(b,batch,passages(b),now).stats.added_student_sessions).toBe(1)})
 it('binds Korean instructions to an explicit sealed protocol revision and rejects old packets',()=>{const b=fixture(),r=b.records[0]!,batch=emptyResponseV2(b) as any,oldManifest=b.protocol_approval!.manifest_hash;batch.student_sessions=[{...structuredClone(r.student_sessions[0]!),blind_item_id:r.blind_item_id,passage_hash:r.passage_hash}];r.student_sessions=[];b.protocol.student_instructions_revision=2;expect(evaluateV2(b,r,text,now).blockers).toContain('protocol_not_sealed_or_changed');seal(b);expect(b.protocol_approval!.manifest_hash).not.toBe(oldManifest);batch.manifest_hash=emptyResponseV2(b).manifest_hash;expect(()=>mergeResponsesV2(b,batch,passages(b),now)).toThrow('Student delivery packet');const packet=deliveryPacketV2(b,r,'student');expect(packet.payload.instructions).toContain('질문을 보기 전에');batch.student_sessions[0].packet_hash=packet.packet_hash;expect(mergeResponsesV2(b,batch,passages(b),now).stats.added_student_sessions).toBe(1)})
 it('old distributed expert packets cannot certify edited sealed anchors or instruments',()=>{const b=fixture(),r=b.records[0]!,batch=emptyResponseV2(b) as any;batch.expert_reviews=structuredClone(r.expert_reviews);r.expert_reviews=[];r.student_sessions=[];b.protocol.score_anchors[0]='Changed synthetic anchor approved before new ratings.';seal(b);batch.manifest_hash=emptyResponseV2(b).manifest_hash;expect(()=>mergeResponsesV2(b,batch,passages(b),now)).toThrow('delivery packet');for(const e of batch.expert_reviews)e.packet_hash=deliveryPacketV2(b,r,'expert').packet_hash;expect(mergeResponsesV2(b,batch,passages(b),now).stats.added_expert_reviews).toBe(2)})
 it('student responses require the newly registered question packet hash',()=>{const b=fixture(),r=b.records[0]!,batch=emptyResponseV2(b) as any;batch.student_sessions=[{...structuredClone(r.student_sessions[0]!),blind_item_id:r.blind_item_id,passage_hash:r.passage_hash}];r.student_sessions=[];r.instrument[0]!.prompt='A newly reviewed synthetic comprehension question.';seal(b);batch.manifest_hash=emptyResponseV2(b).manifest_hash;expect(()=>mergeResponsesV2(b,batch,passages(b),now)).toThrow('Student delivery packet');batch.student_sessions[0].packet_hash=deliveryPacketV2(b,r,'student').packet_hash;expect(mergeResponsesV2(b,batch,passages(b),now).stats.added_student_sessions).toBe(1)})
 it('cannot fill a current partial session using responses from a different packet',()=>{const b=fixture(),r=b.records[0]!,batch=emptyResponseV2(b) as any;batch.student_sessions=[{...structuredClone(r.student_sessions[0]!),blind_item_id:r.blind_item_id,passage_hash:r.passage_hash,packet_hash:'b'.repeat(64)}];r.student_sessions[0]!.answers[0]!.score=null;expect(()=>mergeResponsesV2(b,batch,passages(b),now)).toThrow('Student delivery packet');expect(r.student_sessions[0]!.answers[0]!.score).toBeNull()})
 it.each(['source','uppercase_source','doi','body'])('fixed calibration %s cannot be hidden by different file bytes or exclusion lists',kind=>{const b=fixture(),rules=JSON.parse(fs.readFileSync(new URL('../../../../scripts/textbook/frym-precision/preservation-rules-1.json',import.meta.url),'utf8')),pilotRaw=fs.readFileSync(new URL('../../../../scripts/textbook/frym-precision/adaptation-pilot-1.json',import.meta.url),'utf8'),pilot=JSON.parse(pilotRaw),r=b.records[0]!;b.pilot_hash=researchBodyHash(pilotRaw+'\n');if(kind==='source')r.source_id=rules.entries[0].source_id;if(kind==='uppercase_source')r.source_id=rules.entries[0].source_id.toUpperCase();if(kind==='doi')r.research_doi=rules.entries[0].original_work_id;if(kind==='body')r.passage_hash=researchBodyHash(pilot.records[0].text);expect(()=>assertIndependentOfFixedCalibration(b)).toThrow('Fixed eight-passage');b.protocol.study_purpose='calibration';expect(()=>assertIndependentOfFixedCalibration(b)).not.toThrow()})
 it('preserves a finish-only partial timestamp then fills its missing start',()=>{const b=fixture(),r=b.records[0]!,full=structuredClone(r.student_sessions[0]!),batch=emptyResponseV2(b) as any;r.student_sessions=[];batch.student_sessions=[{...full,reading_started_at:null,blind_item_id:r.blind_item_id,passage_hash:r.passage_hash}];const partial=mergeResponsesV2(b,batch,passages(b),now);expect(partial.bundle.records[0]!.student_sessions[0]!.reading_started_at).toBeNull();expect(evaluateV2(partial.bundle,partial.bundle.records[0]!,text,now).student_count).toBe(0);batch.student_sessions[0].reading_started_at=full.reading_started_at;expect(mergeResponsesV2(partial.bundle,batch,passages(b),now).stats.filled_student_sessions).toBe(1)})
 it('only completed calibration can define subsequent exclusion evidence',()=>{const b=fixture('calibration');expect(calibrationCompletedV2(b,now)).toBe(true);b.records[0]!.student_sessions=[];expect(calibrationCompletedV2(b,now)).toBe(false);for(const e of b.records[0]!.expert_reviews)e.ratings.core_claim.score=2;expect(calibrationCompletedV2(b,now)).toBe(true);b.records[0]!.expert_reviews[1]!.ratings.core_claim.score=4;expect(calibrationCompletedV2(b,now)).toBe(false)})
 it('calibration completion obeys the separately registered grade cohort floor',()=>{const b=fixture('calibration');b.protocol.minimum_students_per_grade=20;for(const grade of ['middle_1','high_1'] as const)for(let n=15;n<20;n++)b.participants.push({student_id:`student-${grade}-${n}`,grade,grade_verified_by:'lead-test',record_order:[`record-${grade}`]});seal(b);expect(evaluateV2(b,b.records[0]!,text,now).blockers).toContain('grade_sample_insufficient');expect(calibrationCompletedV2(b,now)).toBe(false)})
 it('merges atomically, skips identical responses and preserves conflicts',()=>{const b=fixture(),r=b.records[0]!,batch=emptyResponseV2(b) as any;batch.expert_reviews=structuredClone(r.expert_reviews);batch.student_sessions=[{...structuredClone(r.student_sessions[0]!),blind_item_id:r.blind_item_id,passage_hash:r.passage_hash}];r.expert_reviews=[];r.student_sessions=[];const one=mergeResponsesV2(b,batch,passages(b),now);expect(one.stats.added_expert_reviews).toBe(2);expect(one.stats.added_student_sessions).toBe(1);expect(b.records[0]!.student_sessions.length).toBe(0);expect(mergeResponsesV2(one.bundle,batch,passages(b),now).stats.duplicate_responses).toBe(3);batch.expert_reviews[0].reason='Conflicting new synthetic human judgment.';expect(()=>mergeResponsesV2(one.bundle,batch,passages(b),now)).toThrow('Conflicting')})
 it('fills only missing student values and excludes incomplete records',()=>{const b=fixture(),r=b.records[0]!,full=structuredClone(r.student_sessions[0]!),batch=emptyResponseV2(b) as any;r.student_sessions[0]!.answers[0]!.score=null;r.student_sessions[0]!.answers[0]!.scorer_id=null;batch.student_sessions=[{...full,blind_item_id:r.blind_item_id,passage_hash:r.passage_hash}];const result=mergeResponsesV2(b,batch,passages(b),now);expect(result.stats.filled_student_sessions).toBe(1);expect(evaluateV2(result.bundle,result.bundle.records[0]!,text,now).state).toBe('gold');full.answers[0]!.score=.5;batch.student_sessions[0].answers=full.answers;expect(()=>mergeResponsesV2(result.bundle,batch,passages(b),now)).toThrow('Conflicting')})
 it('unsealed nonempty batches and stale manifests cannot collect',()=>{const b=fixture(),batch=emptyResponseV2(b) as any;batch.expert_reviews=[b.records[0]!.expert_reviews[0]!];b.protocol_approval=null;expect(()=>mergeResponsesV2(b,batch,passages(b),now)).toThrow('sealed');batch.manifest_hash=H;expect(()=>mergeResponsesV2(b,batch,passages(b),now)).toThrow('manifest')})
 it('reading before meaning validity and unassigned students cannot collect',()=>{const b=fixture(),r=b.records[0]!,batch=emptyResponseV2(b) as any;batch.student_sessions=[{...r.student_sessions[0]!,blind_item_id:r.blind_item_id,passage_hash:r.passage_hash}];r.student_sessions=[];r.expert_reviews=[];expect(()=>mergeResponsesV2(b,batch,passages(b),now)).toThrow('meaning');batch.student_sessions[0].student_id='unassigned-student';expect(()=>mergeResponsesV2(b,batch,passages(b),now)).toThrow('assignment')})
})
describe('independent validation export (synthetic local evidence only)',()=>{
 it('exports a new round without importing calibration failure IDs into that round',()=>{
  const require=createRequire(import.meta.url),repo=fileURLToPath(new URL('../../../..',import.meta.url)),temp=fs.mkdtempSync(path.join(os.tmpdir(),'fym-v2-export-test-'))
  try{
   const dir=path.join(repo,'scripts/textbook'),round=JSON.parse(fs.readFileSync(path.join(dir,'frym-precision/round-1.json'),'utf8')),rules=JSON.parse(fs.readFileSync(path.join(dir,'frym-precision/preservation-rules-1.json'),'utf8')),pilot=JSON.parse(fs.readFileSync(path.join(dir,'frym-precision/adaptation-pilot-1.json'),'utf8')),protocol=JSON.parse(fs.readFileSync(path.join(dir,'frym-validation/protocol-2.draft.json'),'utf8'))
   protocol.study_purpose='validation'
   const instruments:Record<string,unknown>={}
   for(const p of round.pairs){p.id='NEW-'+p.id;for(const a of p.alignments)a.id='NEW-'+a.id}
   for(const e of rules.entries){e.pair_id='NEW-'+e.pair_id;e.alignment_id='NEW-'+e.alignment_id;const p=round.pairs.find((p:any)=>p.id===e.pair_id),fym='Synthetic source claim for '+e.pair_id+'.',research='Synthetic original research evidence for '+e.pair_id+'.';const oldId=p.source.id;p.source.id='87654321'+oldId.slice(8);const screened=round.selection.screening.find((s:any)=>s.id===oldId);screened.id=p.source.id;p.relation.doi='10.9999/'+p.id.toLowerCase();p.relation.url='https://doi.org/'+p.relation.doi;if(p.metadata)p.metadata.doi=p.relation.doi;screened.declared_dois=[p.relation.doi];e.source_id=p.source.id;e.original_work_id=p.relation.doi;p.source.source_hash=researchBodyHash(fym);p.research.hash=researchBodyHash(research);p.files.fym=e.pair_id+'-fym.txt';p.files.research=e.pair_id+'-research.txt';p.reviewed_spans={fym:[{start:0,end:fym.length,section:'synthetic'}],research:[{start:0,end:research.length,section:'synthetic'}]};for(const a of p.alignments){a.fym_evidence={start:0,end:fym.length,section:'synthetic',quote:fym};a.original_evidence={start:0,end:research.length,section:'synthetic',quote:research};a.omitted_detail=null}e.source_hash=p.source.source_hash;e.research_hash=p.research.hash;e.source_quote=fym;e.research_quote=research;fs.writeFileSync(path.join(temp,p.files.fym),fym);fs.writeFileSync(path.join(temp,p.files.research),research)}
   const roundRaw=JSON.stringify(round);rules.review_hash=researchBodyHash(roundRaw);const rulesRaw=JSON.stringify(rules);pilot.review_hash=rules.review_hash;pilot.rules_hash=researchBodyHash(rulesRaw)
   for(const r of pilot.records){r.id='NEW-'+r.id;r.pair_id='NEW-'+r.pair_id;r.text=text;r.text_hash=researchBodyHash(text);instruments[r.id]=fixture().records[0]!.instrument}
   for(const [name,value] of Object.entries({round:roundRaw,rules:rulesRaw,pilot:JSON.stringify(pilot),protocol:JSON.stringify(protocol),instruments:JSON.stringify(instruments)}))fs.writeFileSync(path.join(temp,name+'.json'),value)
   const output=path.join(temp,'output'),args=['--tsconfig',path.join(repo,'apps/web/tsconfig.json'),path.join(dir,'frym-validation-export.mjs'),'--pilot',path.join(temp,'pilot.json'),'--preservation-rules',path.join(temp,'rules.json'),'--precision-review',path.join(temp,'round.json'),'--protocol',path.join(temp,'protocol.json'),'--instruments',path.join(temp,'instruments.json'),'--study-id','synthetic-new-validation','--evidence-dir',temp,'--output',output]
   execFileSync(process.execPath,[require.resolve('tsx/cli'),...args],{cwd:repo,windowsHide:true})
   const b=bundleV2Schema.parse(JSON.parse(fs.readFileSync(path.join(output,'coordinator/results.json'),'utf8')));expect(b.protocol.study_purpose).toBe('validation');expect(b.records).toHaveLength(8);expect(b.records.every(r=>r.pair_id.startsWith('NEW-'))).toBe(true);expect(b.protocol_approval).toBeNull()
  }finally{if(path.dirname(path.resolve(temp))!==path.resolve(os.tmpdir())||!path.basename(temp).startsWith('fym-v2-export-test-'))throw Error('Unexpected cleanup target');fs.rmSync(temp,{recursive:true,force:true})}
 })
})
