#!/usr/bin/env node
// scripts/design/illo-kaggle.mjs
//
// **Kaggle 무료 GPU 로 tines 화풍 삽화 생성**(DD-68 · tines-mapping §18) — DashScope 무료 한도(100장)를 다 쓴 뒤의 경로.
// Kaggle T4 + Qwen-Image GGUF Q3 + Lightning 4-step(ComfyUI, headless 스크립트 커널). 주 30 GPU시간 무료.
// 실증 레시피: 메모리 project-comic-free-backend · scripts/comic/kaggle/_gen-kernel.py(2026-08).
//
//   node scripts/design/illo-kaggle.mjs                 # 파일이 없는 장면만(재실행 안전)
//   node scripts/design/illo-kaggle.mjs --only a,b      # 몇 개만
//   node scripts/design/illo-kaggle.mjs --force --only a  # 있는 것도 다시
//   node scripts/design/illo-kaggle.mjs --fetch-only    # 이미 돈 커널의 출력만 받아 후처리
//   node scripts/design/illo-kaggle.mjs --variants 3    # 장면마다 시드 3개 → 투명 비율 최고만(4스텝 Lightning 은 cfg=1 이라 부정 프롬프트가 안 먹는다 — 고르기로 거른다)
//
// 흐름: 커널 소스 생성(장면·화풍은 lib/illo-tines-scenes.mjs 단일 출처) → push(T4 강제 · 모델 Dataset 연결)
//       → status 폴링 → output 의 PNG 다운로드 → 바탕 빼기 + WebP(DashScope 경로와 같은 keyAndEncode) → public/illustrations/tines.
// 키: ~/.kaggle/kaggle.json (저장소 밖 — 값은 출력하지 않는다). REST 는 Bearer.
//
// 함정(실측): machineShape 없으면 P100 배정 → torch 미지원 · Dataset 마운트 경로가 커널마다 다르다(os.walk 로 찾는다)
//   · status/output 은 쿼리형 주소만 된다 · /kaggle/working 은 20GB 라 ComfyUI 는 /kaggle/tmp 에.
//   · **커널 이름 하나를 두 세션이 쓰면 나중 push 가 앞 실행을 덮는다**(2026-09-22 — 기출 패턴 16장이 다른 세션의 타일 4장으로
//     바뀌어 「후처리 0장」으로 조용히 끝났다). push 전에 같은 커널이 돌고 있으면 멈추고, 받은 출력이 요청과 안 맞으면 실패한다.
//     동시에 돌리려면 `--slug vocaflow-illo-<이름>` 으로 커널을 나눈다.

import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { ROOT, chromium } from './lib/ref-page.mjs'
import { pathToFileURL } from 'node:url'
import { keyAndEncode } from './lib/illo-tines-scenes.mjs'

const argv = process.argv.slice(2)
const arg = (k, d) => { const i = argv.indexOf(k); return i >= 0 && argv[i + 1] ? argv[i + 1] : d }
const ONLY = arg('--only', null)?.split(',') ?? null
const FORCE = argv.includes('--force')
const FETCH_ONLY = argv.includes('--fetch-only')
/** 장면마다 시드 N개 — 바탕을 뺀 뒤 **투명 비율이 가장 높은 것**을 고른다(물건 뒤에 카드 면이 그려진 결과가 자동 탈락). */
const VARIANTS = Number(arg('--variants', '1'))
// `--scenes <모듈>` — 다른 파이프라인이 자기 장면 목록(SCENES · NEG)을 넘긴다(예: scripts/vcb/editions/edition-scenes.mjs).
//   없으면 tines 삽화. `--out` 은 산출 폴더(저장소 루트 기준).
const SCENES_MOD = arg('--scenes', './lib/illo-tines-scenes.mjs')
const { NEG, SCENES } = await import(SCENES_MOD.startsWith('./lib/') ? SCENES_MOD : pathToFileURL(path.resolve(ROOT, SCENES_MOD)).href)
const OUT = path.join(ROOT, arg('--out', 'apps/web/public/illustrations/tines'))
const WORK = path.join(ROOT, 'tmp', arg('--slug', 'vocaflow-illo-tines'))
const DATASET = 'minkang123/vocaflow-qwen-comic'
const SLUG = arg('--slug', 'vocaflow-illo-tines')

const cred = JSON.parse(fs.readFileSync(path.join(os.homedir(), '.kaggle/kaggle.json'), 'utf8'))
const USER = String(cred.username).toLowerCase()
const H = { Authorization: `Bearer ${cred.key}`, 'Content-Type': 'application/json' }
const API = 'https://www.kaggle.com/api/v1'

/** DashScope 크기 표기 → T4 에서 도는 크기(8 의 배수). 표시는 300px 이하라 1024 면 충분하다. */
const sizeOf = (s) => (s.size === '1664*928' ? [1344, 768] : s.size === '1472*1140' ? [1152, 896] : [1024, 1024])

function kernelSource(jobs) {
  const payload = Buffer.from(JSON.stringify(jobs)).toString('base64')
  return `# vocaflow tines illustrations — generated by scripts/design/illo-kaggle.mjs (do not edit)
import os, subprocess, sys, time, json, base64, urllib.request
os.makedirs('/kaggle/working/out', exist_ok=True)
COMFY='/kaggle/tmp/ComfyUI'; os.makedirs('/kaggle/tmp', exist_ok=True)
def sh(*a, **k): return subprocess.run(list(a), **k)
sh('git','clone','https://github.com/comfyanonymous/ComfyUI', COMFY)
_sha=subprocess.run(['git','-C',COMFY,'rev-list','-1','--before=2025-11-01','HEAD'],capture_output=True,text=True).stdout.strip()
if _sha: sh('git','-C',COMFY,'checkout',_sha)
sh('git','clone','--depth','1','https://github.com/city96/ComfyUI-GGUF', COMFY+'/custom_nodes/ComfyUI-GGUF')
sh(sys.executable,'-m','pip','-q','install','torch==2.6.0','torchvision==0.21.0','--index-url','https://download.pytorch.org/whl/cu124')
_lines=open(COMFY+'/requirements.txt').read().splitlines()
def _pk(r): return r.strip().split('==')[0].split('>')[0].split('<')[0].split('~')[0].split(';')[0].strip().lower()
open('/kaggle/tmp/req.txt','w').write('\\n'.join([r for r in _lines if r.strip() and not r.strip().startswith('#') and _pk(r) not in ('torch','torchvision','torchaudio')]))
sh(sys.executable,'-m','pip','-q','install','-r','/kaggle/tmp/req.txt','gguf')
import torch; print('GPU:', torch.cuda.get_device_name(0), torch.__version__, flush=True)
# Dataset 마운트 경로는 커널마다 다르다 — 앵커 파일로 찾는다
DS=None
for r,_,fs_ in os.walk('/kaggle/input'):
    if 'qwen-image-Q3_K_S.gguf' in fs_: DS=r; break
print('DS', DS, flush=True)
def link(name, sub):
    d=COMFY+'/models/'+sub; os.makedirs(d, exist_ok=True)
    dst=d+'/'+name
    if not os.path.lexists(dst): os.symlink(DS+'/'+name, dst)
link('qwen-image-Q3_K_S.gguf','unet'); link('qwen2.5-vl-7b-it-q4_k_m.gguf','text_encoders'); link('mmproj-qwen2.5-vl-7b-it-bf16.gguf','text_encoders')
link('qwen_image_vae.safetensors','vae'); link('Qwen-Image-Lightning-4steps-V1.0-bf16.safetensors','loras')
subprocess.Popen([sys.executable,'-u','main.py','--listen','127.0.0.1','--port','8188','--lowvram','--output-directory','/kaggle/tmp/comfy-out'],
                 cwd=COMFY, stdout=open('/kaggle/working/out/_comfy.log','w'), stderr=subprocess.STDOUT)
def up():
    try: urllib.request.urlopen('http://127.0.0.1:8188/system_stats', timeout=3); return True
    except Exception: return False
for _ in range(120):
    if up(): break
    time.sleep(5)
print('comfy up', up(), flush=True)
def call(p, data=None):
    req=urllib.request.Request('http://127.0.0.1:8188'+p, data=(json.dumps(data).encode() if data is not None else None), headers={'Content-Type':'application/json'})
    return json.loads(urllib.request.urlopen(req, timeout=300).read())
JOBS=json.loads(base64.b64decode("${payload}").decode())
res=[]
for j in JOBS:
    t=time.time()
    wf={
     "1":{"class_type":"UnetLoaderGGUF","inputs":{"unet_name":"qwen-image-Q3_K_S.gguf"}},
     "2":{"class_type":"CLIPLoaderGGUF","inputs":{"clip_name":"qwen2.5-vl-7b-it-q4_k_m.gguf","type":"qwen_image"}},
     "3":{"class_type":"VAELoader","inputs":{"vae_name":"qwen_image_vae.safetensors"}},
     "4":{"class_type":"CLIPTextEncode","inputs":{"text":j["prompt"],"clip":["2",0]}},
     "5":{"class_type":"CLIPTextEncode","inputs":{"text":j["neg"],"clip":["2",0]}},
     "6":{"class_type":"EmptySD3LatentImage","inputs":{"width":j["w"],"height":j["h"],"batch_size":1}},
     "11":{"class_type":"LoraLoaderModelOnly","inputs":{"lora_name":"Qwen-Image-Lightning-4steps-V1.0-bf16.safetensors","strength_model":1,"model":["1",0]}},
     "7":{"class_type":"ModelSamplingAuraFlow","inputs":{"shift":3.1,"model":["11",0]}},
     "8":{"class_type":"KSampler","inputs":{"seed":j["seed"],"steps":4,"cfg":1,"sampler_name":"euler","scheduler":"simple","denoise":1,"model":["7",0],"positive":["4",0],"negative":["5",0],"latent_image":["6",0]}},
     "9":{"class_type":"VAEDecode","inputs":{"samples":["8",0],"vae":["3",0]}},
     "10":{"class_type":"SaveImage","inputs":{"images":["9",0],"filename_prefix":j["id"]}}}
    try:
        pid=call('/prompt',{'prompt':wf,'client_id':'illo'})['prompt_id']
        done=None
        for _ in range(240):
            h=call('/history/'+pid)
            if pid in h and h[pid].get('outputs'): done=h[pid]; break
            if pid in h and h[pid].get('status',{}).get('status_str')=='error': break
            time.sleep(3)
        if not done: raise Exception('no output')
        im=done['outputs']['10']['images'][0]
        src=os.path.join('/kaggle/tmp/comfy-out', im.get('subfolder',''), im['filename'])
        dst='/kaggle/working/out/'+j['id']+'.png'
        with open(src,'rb') as a, open(dst,'wb') as b: b.write(a.read())
        res.append({'id':j['id'],'ok':True,'sec':round(time.time()-t)})
        print('ok', j['id'], round(time.time()-t), 's', flush=True)
    except Exception as e:
        res.append({'id':j['id'],'ok':False,'err':str(e)[:200]}); print('fail', j['id'], e, flush=True)
json.dump(res, open('/kaggle/working/out/_results.json','w'))
print('DONE', sum(1 for r in res if r['ok']), '/', len(res), flush=True)
`
}

async function api(p, init = {}) {
  const r = await fetch(API + p, { ...init, headers: { ...H, ...(init.headers || {}) } })
  const t = await r.text()
  let j = null
  try { j = JSON.parse(t) } catch { /* 본문이 JSON 이 아님 */ }
  if (!r.ok) throw new Error(`${p} → ${r.status} ${t.slice(0, 300)}`)
  return j
}

// 제목도 커널마다 달라야 한다 — 같은 제목이면 push 가 409 (newTitle 은 slug 에서 만든다)
async function push(jobs) {
  // 같은 커널이 돌고 있으면 새 버전이 그 실행을 덮는다 — 멈춘다(위 함정)
  const cur = await api(`/kernels/status?userName=${USER}&kernelSlug=${SLUG}`).catch(() => null)
  if (/running|queued/.test(String(cur?.status ?? '').toLowerCase())) {
    console.error(`커널 ${SLUG} 이 이미 ${cur.status} — 다른 실행을 덮게 된다. 끝나기를 기다리거나 --slug 로 다른 커널을 쓴다`)
    process.exit(3)
  }
  const body = {
    slug: `${USER}/${SLUG}`, newTitle: SLUG.replace(/-/g, ' '), text: kernelSource(jobs), language: 'python', kernelType: 'script',
    isPrivate: true, enableGpu: true, enableInternet: true, machineShape: 'NvidiaTeslaT4',
    datasetDataSources: [DATASET], competitionDataSources: [], kernelDataSources: [], modelDataSources: [], categoryIds: [],
  }
  const j = await api('/kernels/push', { method: 'POST', body: JSON.stringify(body) })
  if (j?.error) throw new Error(`push: ${j.error}`)
  console.log(`push → ${j?.url ?? '(url 없음)'} · 버전 ${j?.versionNumber ?? '?'}${j?.invalidDatasetSources?.length ? ' · ⚠ 잘못된 Dataset ' + j.invalidDatasetSources : ''}`)
}

async function waitDone() {
  const t0 = Date.now()
  for (;;) {
    const s = await api(`/kernels/status?userName=${USER}&kernelSlug=${SLUG}`).catch((e) => ({ status: 'poll-error ' + e.message }))
    const st = String(s?.status ?? '').toLowerCase()
    process.stdout.write(`\r상태 ${st.padEnd(12)} ${Math.round((Date.now() - t0) / 1000)}s   `)
    if (/complete/.test(st)) { console.log(); return true }
    if (/error|cancel/.test(st)) { console.log(`\n실패 ${JSON.stringify(s).slice(0, 300)}`); return false }
    await new Promise((z) => setTimeout(z, 30_000))
  }
}

async function fetchOutputs() {
  fs.mkdirSync(WORK, { recursive: true })
  let token = null, got = []
  do {
    const q = `/kernels/output?userName=${USER}&kernelSlug=${SLUG}${token ? `&pageToken=${encodeURIComponent(token)}` : ''}`
    const j = await api(q)
    if (j?.logNullable || j?.log) fs.writeFileSync(path.join(WORK, 'kernel.log'), String(j.logNullable ?? j.log))
    for (const f of j?.files ?? []) {
      const name = path.basename(f.fileName ?? f.name ?? '')
      if (!/\.(png|json|log)$/.test(name)) continue
      const buf = Buffer.from(await (await fetch(f.url)).arrayBuffer())
      fs.writeFileSync(path.join(WORK, name), buf)
      got.push(name)
    }
    token = j?.nextPageToken || null
  } while (token)
  console.log(`출력 ${got.length}개 받음 → ${path.relative(ROOT, WORK)}`)
  return got.filter((n) => n.endsWith('.png') && !n.startsWith('_'))
}

async function postprocess(pngs) {
  const byId = Object.fromEntries(SCENES.map((s) => [s.id, s]))
  const b = await chromium.launch()
  const pg = await b.newPage()
  // 바탕을 뺀 결과에서 완전히 투명한 화소의 비율 — 물건 하나가 빈 바탕 위에 있으면 높고, 카드 면이 깔렸으면 낮다
  const clearRatio = (b64) => pg.evaluate(async (src) => {
    const im = new Image(); im.src = src; await im.decode()
    const c = document.createElement('canvas'); c.width = im.width; c.height = im.height
    const g = c.getContext('2d'); g.drawImage(im, 0, 0)
    const d = g.getImageData(0, 0, c.width, c.height).data
    let z = 0; for (let i = 3; i < d.length; i += 16) if (d[i] === 0) z++
    return z / (d.length / 16)
  }, 'data:image/webp;base64,' + b64)
  // Kaggle(Q3 + Lightning) 은 타일 안쪽에 둥근 테두리 액자를 한 겹 더 그린다(앱 아이콘 모양 — 2026-09-22 실측, 두 장 다).
  //   참조 타일은 면이 가장자리까지 꽉 차므로 **사방 10% 를 잘라** 액자를 걷는다. 물건은 가운데 50% 라 잘리지 않는다.
  const cropInset = (src, ratio) => pg.evaluate(async ([data, ratio]) => {
    const im = new Image(); im.src = data; await im.decode()
    const inset = Math.round(im.width * ratio), S = im.width - inset * 2
    const c = document.createElement('canvas'); c.width = 1024; c.height = 1024
    c.getContext('2d').drawImage(im, inset, inset, S, S, 0, 0, 1024, 1024)
    return c.toDataURL('image/png')
  }, [src, ratio])
  const groups = new Map()
  for (const f of pngs) {
    const base = f.replace(/\.png$/, '').replace(/__v\d+$/, '')
    if (!byId[base]) continue
    if (!groups.has(base)) groups.set(base, [])
    groups.get(base).push(f)
  }
  let n = 0
  for (const [id, files] of groups) {
    const s = byId[id]
    let best = null
    for (const f of files) {
      let src = 'data:image/png;base64,' + fs.readFileSync(path.join(WORK, f)).toString('base64')
      // 장면이 `crop` 을 주면 그 비율로(에디션 표지 — 같은 액자가 정사각 표지에도 그려진다, 2026-09-25 28장 중 6장)
      const crop = s.crop ?? (id.startsWith('tile-') ? 0.1 : 0)
      if (crop) src = await cropInset(src, crop)
      const b64 = await pg.evaluate(keyAndEncode, [src, s.key])
      const score = s.key === false ? 0 : await clearRatio(b64)
      if (!best || score > best.score) best = { b64, score, f }
    }
    fs.writeFileSync(path.join(OUT, id + '.webp'), Buffer.from(best.b64, 'base64'))
    n++
    console.log('  ✓ ' + id + (files.length > 1 ? ' ← ' + best.f + ' (투명 ' + Math.round(best.score * 100) + '% · 후보 ' + files.length + ')' : ''))
  }
  await b.close()
  console.log('후처리 ' + n + '장 → ' + path.relative(ROOT, OUT))
}

if (!FETCH_ONLY) {
  const todo = SCENES.filter((s) => (!ONLY || ONLY.includes(s.id)) && (FORCE || !fs.existsSync(path.join(OUT, `${s.id}.webp`))))
  if (!todo.length) { console.log('만들 장면이 없다(전부 있음) — --force 로 다시'); process.exit(0) }
  const jobs = todo.flatMap((s) => {
    const [w, h] = sizeOf(s)
    return Array.from({ length: VARIANTS }, (_, k) => ({ id: VARIANTS > 1 ? `${s.id}__v${k}` : s.id, prompt: `${s.scene} ${s.style}`, neg: NEG, w, h, seed: Math.floor(Math.random() * 2 ** 40) }))
  })
  console.log(`생성 ${jobs.length}: ${jobs.map((j) => j.id).join(' ')}`)
  await push(jobs)
  await new Promise((z) => setTimeout(z, 20_000))
  if (!(await waitDone())) { await fetchOutputs().catch(() => {}); process.exit(1) }
}
const pngs = await fetchOutputs()
if (!FETCH_ONLY) {
  // 받은 출력이 이번 요청의 것인지 — 다른 실행이 같은 커널을 덮었으면 이름이 하나도 안 맞는다
  const asked = new Set(SCENES.filter((s) => (!ONLY || ONLY.includes(s.id))).map((s) => s.id))
  const mine = pngs.filter((n) => asked.has(n.replace(/\.png$/, '').replace(/__v\d+$/, '')))
  if (!mine.length) {
    console.error(`출력 ${pngs.length}장이 요청한 장면과 하나도 안 맞는다(${pngs.slice(0, 4).join(', ')}) — 같은 커널(${SLUG})을 다른 실행이 덮었다. --slug 로 나눠 다시`)
    process.exit(4)
  }
}
await postprocess(pngs)
