// apps/web/src/components/flashcard/mock-data.ts

import { createNewCard } from '@/lib/srs'
import { createInitialSRS } from '@/lib/srs/sm2'
import type { FlashcardWord } from '@/types/flashcard'

export const MOCK_FLASHCARD_WORDS: FlashcardWord[] = [
  {
    id: 'fw1',
    text: 'vulnerable',
    meaning: '취약한, 상처받기 쉬운',
    pronunciation: '/ˈvʌlnərəbl/',
    pos: 'adj.',
    exampleSentence: 'In my younger and more vulnerable years my father gave me some advice.',
    exampleSentenceWithBlank: 'In my younger and more ___ years my father gave me some advice.',
    textId: '1',
    textTitle: 'The Great Gatsby',
    textChapter: 'Chapter 1',
    srs: createInitialSRS(),
    srsV2: createNewCard('fw1'),
  },
  {
    id: 'fw2',
    text: 'criticize',
    meaning: '비판하다, 비난하다',
    pronunciation: '/ˈkrɪtɪˌsaɪz/',
    pos: 'v.',
    exampleSentence: 'Whenever you feel like criticizing any one, just remember.',
    exampleSentenceWithBlank: 'Whenever you feel like ___ any one, just remember.',
    textId: '1',
    textTitle: 'The Great Gatsby',
    textChapter: 'Chapter 1',
    srs: createInitialSRS(),
    srsV2: createNewCard('fw2'),
  },
  {
    id: 'fw3',
    text: 'reserved',
    meaning: '내성적인, 신중한',
    pronunciation: '/rɪˈzɜːrvd/',
    pos: 'adj.',
    exampleSentence: 'We have always been unusually communicative in a reserved way.',
    exampleSentenceWithBlank: 'We have always been unusually communicative in a ___ way.',
    textId: '1',
    textTitle: 'The Great Gatsby',
    textChapter: 'Chapter 1',
    srs: createInitialSRS(),
    srsV2: createNewCard('fw3'),
  },
  {
    id: 'fw4',
    text: 'consequence',
    meaning: '결과, 영향',
    pronunciation: '/ˈkɒnsɪkwəns/',
    pos: 'n.',
    exampleSentence: "In consequence, I'm inclined to reserve all judgments.",
    exampleSentenceWithBlank: "In ___, I'm inclined to reserve all judgments.",
    textId: '1',
    textTitle: 'The Great Gatsby',
    textChapter: 'Chapter 1',
    srs: createInitialSRS(),
    srsV2: createNewCard('fw4'),
  },
  {
    id: 'fw5',
    text: 'inclined',
    meaning: '~하는 경향이 있는',
    pronunciation: '/ɪnˈklaɪnd/',
    pos: 'adj.',
    exampleSentence: "I'm inclined to reserve all judgments.",
    exampleSentenceWithBlank: "I'm ___ to reserve all judgments.",
    textId: '1',
    textTitle: 'The Great Gatsby',
    textChapter: 'Chapter 1',
    srs: createInitialSRS(),
    srsV2: createNewCard('fw5'),
  },
]
