// apps/web/src/components/wordvault/mock-data.ts
// WordVault 데모 데이터

import type { WordItem } from './types'

export const MOCK_WORDS: WordItem[] = [
  {
    id: 1,
    word: 'persistence',
    pos: 'n.',
    meaning: '끈기, 지속성',
    exampleEn: 'Practice and persistence pay off in the long run.',
    level: 'C1',
    levelClass: 'c',
    mastery: 4,
    lastDays: 2,
    nextDays: 3,
  },
  {
    id: 2,
    word: 'remarkable',
    pos: 'adj.',
    meaning: '주목할 만한, 놀랄 만한',
    exampleEn: 'Yesterday I went to a remarkable bookstore downtown.',
    level: 'B2',
    levelClass: 'b',
    mastery: 3,
    lastDays: 3,
    nextDays: 5,
  },
  {
    id: 3,
    word: 'fascinating',
    pos: 'adj.',
    meaning: '매혹적인, 흥미로운',
    exampleEn: 'I discovered a fascinating biography about an artist.',
    level: 'B1',
    levelClass: 'b',
    mastery: 2,
    lastDays: 5,
    nextDays: 1,
  },
  {
    id: 4,
    word: 'obscure',
    pos: 'adj.',
    meaning: '잘 알려지지 않은, 모호한',
    exampleEn: 'It was about an obscure Renaissance artist.',
    level: 'C1',
    levelClass: 'c',
    mastery: 5,
    lastDays: 7,
    nextDays: 14,
  },
  {
    id: 5,
    word: 'cozy',
    pos: 'adj.',
    meaning: '아늑한, 편안한',
    exampleEn: 'The atmosphere was incredibly cozy and warm.',
    level: 'B2',
    levelClass: 'b',
    mastery: 5,
    lastDays: 7,
    nextDays: 14,
  },
  {
    id: 6,
    word: 'atmosphere',
    pos: 'n.',
    meaning: '분위기, 대기',
    exampleEn: 'The atmosphere of the cafe was warm and welcoming.',
    level: 'B1',
    levelClass: 'b',
    mastery: 4,
    lastDays: 14,
    nextDays: 7,
  },
  {
    id: 7,
    word: 'incredibly',
    pos: 'adv.',
    meaning: '믿을 수 없을 정도로',
    exampleEn: 'The view from the mountain was incredibly beautiful.',
    level: 'B2',
    levelClass: 'b',
    mastery: 2,
    lastDays: 5,
    nextDays: 1,
  },
  {
    id: 8,
    word: 'discovered',
    pos: 'v.',
    meaning: '발견했다',
    exampleEn: 'She discovered a new species of butterfly.',
    level: 'A2',
    levelClass: 'a',
    mastery: 4,
    lastDays: 14,
    nextDays: 7,
  },
]

export const MOCK_COLLECTIONS = [
  { id: 'all', name: '전체', count: 342 },
  { id: 'gatsby', name: 'The Great Gatsby', count: 156 },
  { id: '1984', name: '1984', count: 89 },
  { id: 'ted', name: 'TED', count: 47 },
  { id: 'bbc', name: 'BBC', count: 23 },
  { id: 'favorites', name: '즐겨찾기', count: 28 },
]
