// apps/web/src/components/text-viewer/analysis-types.ts
// TextViewer 분석 결과 데이터 타입

export type CefrLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2'

export interface ExtractedWord {
  id: string
  /** 원문에 있던 형태 */
  word: string
  /** 표제어 (lemma) */
  lemma: string
  /** CEFR 난이도 */
  level: CefrLevel
  /** 한국어 의미 (간단) */
  meaning: string
  /** 품사 */
  partOfSpeech: 'n.' | 'v.' | 'adj.' | 'adv.' | 'prep.' | 'conj.' | 'pron.'
  /** 원문에서 등장 횟수 */
  frequency: number
  /** 원문 내 첫 등장 인덱스 (하이라이트용) */
  firstIndex?: number
}

export interface AnalysisResult {
  /** 원문 */
  text: string
  /** 단어 수 */
  totalWords: number
  /** 문자 수 */
  totalChars: number
  /** 추출된 학습 단어 */
  words: ExtractedWord[]
  /** 분석 소요 시간 (ms) */
  duration: number
}

// ══════════════════════════════════════════════════════════════
// 목업 데이터 (Phase 2에서 OpenAI 호출로 교체)
// ══════════════════════════════════════════════════════════════
export const mockAnalysisResult: AnalysisResult = {
  text: `The quick brown fox jumps over the lazy dog. The rain in Spain falls mainly on the plain. A journey of a thousand miles begins with a single step. The early bird catches the worm, but the second mouse gets the cheese. Practice makes perfect, and persistence pays off.

Yesterday I went to a remarkable bookstore downtown. The atmosphere was incredibly cozy, with vintage chandeliers casting warm light on countless shelves. I discovered a fascinating biography about an obscure Renaissance artist who revolutionized fresco techniques. The narrative was so captivating that I lost track of time entirely.`,
  totalWords: 78,
  totalChars: 487,
  duration: 1247,
  words: [
    {
      id: 'w1',
      word: 'quick',
      lemma: 'quick',
      level: 'A2',
      meaning: '빠른, 신속한',
      partOfSpeech: 'adj.',
      frequency: 1,
    },
    {
      id: 'w2',
      word: 'brown',
      lemma: 'brown',
      level: 'A1',
      meaning: '갈색의',
      partOfSpeech: 'adj.',
      frequency: 1,
    },
    {
      id: 'w3',
      word: 'jumps',
      lemma: 'jump',
      level: 'A1',
      meaning: '뛰어오르다',
      partOfSpeech: 'v.',
      frequency: 1,
    },
    {
      id: 'w4',
      word: 'lazy',
      lemma: 'lazy',
      level: 'A2',
      meaning: '게으른',
      partOfSpeech: 'adj.',
      frequency: 1,
    },
    {
      id: 'w5',
      word: 'rain',
      lemma: 'rain',
      level: 'A1',
      meaning: '비',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w6',
      word: 'falls',
      lemma: 'fall',
      level: 'A1',
      meaning: '떨어지다',
      partOfSpeech: 'v.',
      frequency: 1,
    },
    {
      id: 'w7',
      word: 'mainly',
      lemma: 'mainly',
      level: 'B1',
      meaning: '주로',
      partOfSpeech: 'adv.',
      frequency: 1,
    },
    {
      id: 'w8',
      word: 'plain',
      lemma: 'plain',
      level: 'B1',
      meaning: '평원, 평지',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w9',
      word: 'journey',
      lemma: 'journey',
      level: 'A2',
      meaning: '여행, 여정',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w10',
      word: 'thousand',
      lemma: 'thousand',
      level: 'A1',
      meaning: '천(1000)',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w11',
      word: 'begins',
      lemma: 'begin',
      level: 'A1',
      meaning: '시작하다',
      partOfSpeech: 'v.',
      frequency: 1,
    },
    {
      id: 'w12',
      word: 'single',
      lemma: 'single',
      level: 'A2',
      meaning: '하나의, 단일의',
      partOfSpeech: 'adj.',
      frequency: 1,
    },
    {
      id: 'w13',
      word: 'early',
      lemma: 'early',
      level: 'A1',
      meaning: '이른, 일찍',
      partOfSpeech: 'adj.',
      frequency: 1,
    },
    {
      id: 'w14',
      word: 'bird',
      lemma: 'bird',
      level: 'A1',
      meaning: '새',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w15',
      word: 'catches',
      lemma: 'catch',
      level: 'A1',
      meaning: '잡다',
      partOfSpeech: 'v.',
      frequency: 1,
    },
    {
      id: 'w16',
      word: 'worm',
      lemma: 'worm',
      level: 'B1',
      meaning: '벌레, 지렁이',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w17',
      word: 'second',
      lemma: 'second',
      level: 'A1',
      meaning: '두 번째의',
      partOfSpeech: 'adj.',
      frequency: 1,
    },
    {
      id: 'w18',
      word: 'mouse',
      lemma: 'mouse',
      level: 'A1',
      meaning: '쥐',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w19',
      word: 'cheese',
      lemma: 'cheese',
      level: 'A1',
      meaning: '치즈',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w20',
      word: 'practice',
      lemma: 'practice',
      level: 'A2',
      meaning: '연습',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w21',
      word: 'perfect',
      lemma: 'perfect',
      level: 'A2',
      meaning: '완벽한',
      partOfSpeech: 'adj.',
      frequency: 1,
    },
    {
      id: 'w22',
      word: 'persistence',
      lemma: 'persistence',
      level: 'C1',
      meaning: '끈기, 지속성',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w23',
      word: 'pays',
      lemma: 'pay',
      level: 'A1',
      meaning: '지불하다',
      partOfSpeech: 'v.',
      frequency: 1,
    },
    {
      id: 'w24',
      word: 'remarkable',
      lemma: 'remarkable',
      level: 'B2',
      meaning: '주목할 만한',
      partOfSpeech: 'adj.',
      frequency: 1,
    },
    {
      id: 'w25',
      word: 'bookstore',
      lemma: 'bookstore',
      level: 'A2',
      meaning: '서점',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w26',
      word: 'downtown',
      lemma: 'downtown',
      level: 'B1',
      meaning: '시내, 번화가',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w27',
      word: 'atmosphere',
      lemma: 'atmosphere',
      level: 'B1',
      meaning: '분위기',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w28',
      word: 'incredibly',
      lemma: 'incredibly',
      level: 'B2',
      meaning: '믿을 수 없을 정도로',
      partOfSpeech: 'adv.',
      frequency: 1,
    },
    {
      id: 'w29',
      word: 'cozy',
      lemma: 'cozy',
      level: 'B2',
      meaning: '아늑한',
      partOfSpeech: 'adj.',
      frequency: 1,
    },
    {
      id: 'w30',
      word: 'vintage',
      lemma: 'vintage',
      level: 'B2',
      meaning: '빈티지의',
      partOfSpeech: 'adj.',
      frequency: 1,
    },
    {
      id: 'w31',
      word: 'chandeliers',
      lemma: 'chandelier',
      level: 'C1',
      meaning: '샹들리에',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w32',
      word: 'casting',
      lemma: 'cast',
      level: 'B1',
      meaning: '비추다, 던지다',
      partOfSpeech: 'v.',
      frequency: 1,
    },
    {
      id: 'w33',
      word: 'warm',
      lemma: 'warm',
      level: 'A1',
      meaning: '따뜻한',
      partOfSpeech: 'adj.',
      frequency: 1,
    },
    {
      id: 'w34',
      word: 'countless',
      lemma: 'countless',
      level: 'B2',
      meaning: '수많은',
      partOfSpeech: 'adj.',
      frequency: 1,
    },
    {
      id: 'w35',
      word: 'shelves',
      lemma: 'shelf',
      level: 'A2',
      meaning: '선반',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w36',
      word: 'discovered',
      lemma: 'discover',
      level: 'A2',
      meaning: '발견하다',
      partOfSpeech: 'v.',
      frequency: 1,
    },
    {
      id: 'w37',
      word: 'fascinating',
      lemma: 'fascinating',
      level: 'B1',
      meaning: '매혹적인',
      partOfSpeech: 'adj.',
      frequency: 1,
    },
    {
      id: 'w38',
      word: 'biography',
      lemma: 'biography',
      level: 'B1',
      meaning: '전기, 일대기',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w39',
      word: 'obscure',
      lemma: 'obscure',
      level: 'C1',
      meaning: '잘 알려지지 않은',
      partOfSpeech: 'adj.',
      frequency: 1,
    },
    {
      id: 'w40',
      word: 'Renaissance',
      lemma: 'Renaissance',
      level: 'B2',
      meaning: '르네상스',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w41',
      word: 'artist',
      lemma: 'artist',
      level: 'A1',
      meaning: '예술가',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w42',
      word: 'revolutionized',
      lemma: 'revolutionize',
      level: 'C1',
      meaning: '혁명을 일으키다',
      partOfSpeech: 'v.',
      frequency: 1,
    },
    {
      id: 'w43',
      word: 'fresco',
      lemma: 'fresco',
      level: 'C2',
      meaning: '프레스코화',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w44',
      word: 'techniques',
      lemma: 'technique',
      level: 'B1',
      meaning: '기법, 기술',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w45',
      word: 'narrative',
      lemma: 'narrative',
      level: 'B2',
      meaning: '서술, 이야기',
      partOfSpeech: 'n.',
      frequency: 1,
    },
    {
      id: 'w46',
      word: 'captivating',
      lemma: 'captivating',
      level: 'C1',
      meaning: '마음을 사로잡는',
      partOfSpeech: 'adj.',
      frequency: 1,
    },
    {
      id: 'w47',
      word: 'entirely',
      lemma: 'entirely',
      level: 'B1',
      meaning: '완전히',
      partOfSpeech: 'adv.',
      frequency: 1,
    },
  ],
}
