-- supabase/migrations/20260613150000_inflected_forms_irregulars.sql
-- 굴절형 Phase C — 불규칙 권위 패러다임 (closed set).
--
-- Phase A 부트스트랩(freq corpus 필터)은 다수 불규칙을 잡았으나 일부 누락(leave→left)·noise
-- (comer/gonna/runny) 잔존. 규칙형은 matchSurface 가 처리하므로 DB는 불규칙만 있으면 충분.
-- 영어 불규칙 동사/명사(학습자 빈출 closed set)의 정식 굴절 surface 를 권위 입력 → 해당 lemma 의
-- inflected_forms 를 REPLACE (noise 제거 + 누락 보강). 목록 외 lemma 의 부트스트랩 값은 보존.
--   ※ 학습대상은 항상 lemma — inflected_forms 는 인식/표시 메타데이터.

WITH irr(lemma, forms) AS (VALUES
  -- ── 불규칙 동사 (3sg · -ing · past · past participle, base 제외) ──
  ('be',        ARRAY['am','is','are','was','were','been','being']),
  ('have',      ARRAY['has','had','having']),
  ('do',        ARRAY['does','did','done','doing']),
  ('go',        ARRAY['goes','going','went','gone']),
  ('say',       ARRAY['says','saying','said']),
  ('get',       ARRAY['gets','getting','got','gotten']),
  ('make',      ARRAY['makes','making','made']),
  ('know',      ARRAY['knows','knowing','knew','known']),
  ('think',     ARRAY['thinks','thinking','thought']),
  ('take',      ARRAY['takes','taking','took','taken']),
  ('see',       ARRAY['sees','seeing','saw','seen']),
  ('come',      ARRAY['comes','coming','came']),
  ('find',      ARRAY['finds','finding','found']),
  ('give',      ARRAY['gives','giving','gave','given']),
  ('tell',      ARRAY['tells','telling','told']),
  ('feel',      ARRAY['feels','feeling','felt']),
  ('become',    ARRAY['becomes','becoming','became']),
  ('leave',     ARRAY['leaves','leaving','left']),
  ('mean',      ARRAY['means','meaning','meant']),
  ('keep',      ARRAY['keeps','keeping','kept']),
  ('begin',     ARRAY['begins','beginning','began','begun']),
  ('show',      ARRAY['shows','showing','showed','shown']),
  ('hear',      ARRAY['hears','hearing','heard']),
  ('run',       ARRAY['runs','running','ran']),
  ('hold',      ARRAY['holds','holding','held']),
  ('bring',     ARRAY['brings','bringing','brought']),
  ('write',     ARRAY['writes','writing','wrote','written']),
  ('sit',       ARRAY['sits','sitting','sat']),
  ('stand',     ARRAY['stands','standing','stood']),
  ('lose',      ARRAY['loses','losing','lost']),
  ('pay',       ARRAY['pays','paying','paid']),
  ('meet',      ARRAY['meets','meeting','met']),
  ('set',       ARRAY['sets','setting']),
  ('lead',      ARRAY['leads','leading','led']),
  ('understand',ARRAY['understands','understanding','understood']),
  ('speak',     ARRAY['speaks','speaking','spoke','spoken']),
  ('spend',     ARRAY['spends','spending','spent']),
  ('grow',      ARRAY['grows','growing','grew','grown']),
  ('win',       ARRAY['wins','winning','won']),
  ('teach',     ARRAY['teaches','teaching','taught']),
  ('buy',       ARRAY['buys','buying','bought']),
  ('send',      ARRAY['sends','sending','sent']),
  ('build',     ARRAY['builds','building','built']),
  ('fall',      ARRAY['falls','falling','fell','fallen']),
  ('cut',       ARRAY['cuts','cutting']),
  ('sell',      ARRAY['sells','selling','sold']),
  ('break',     ARRAY['breaks','breaking','broke','broken']),
  ('eat',       ARRAY['eats','eating','ate','eaten']),
  ('catch',     ARRAY['catches','catching','caught']),
  ('draw',      ARRAY['draws','drawing','drew','drawn']),
  ('choose',    ARRAY['chooses','choosing','chose','chosen']),
  ('fight',     ARRAY['fights','fighting','fought']),
  ('fly',       ARRAY['flies','flying','flew','flown']),
  ('drive',     ARRAY['drives','driving','drove','driven']),
  ('wear',      ARRAY['wears','wearing','wore','worn']),
  ('throw',     ARRAY['throws','throwing','threw','thrown']),
  ('deal',      ARRAY['deals','dealing','dealt']),
  ('forget',    ARRAY['forgets','forgetting','forgot','forgotten']),
  ('ride',      ARRAY['rides','riding','rode','ridden']),
  ('rise',      ARRAY['rises','rising','rose','risen']),
  ('drink',     ARRAY['drinks','drinking','drank','drunk']),
  ('swim',      ARRAY['swims','swimming','swam','swum']),
  ('sing',      ARRAY['sings','singing','sang','sung']),
  ('ring',      ARRAY['rings','ringing','rang','rung']),
  ('sink',      ARRAY['sinks','sinking','sank','sunk']),
  ('shoot',     ARRAY['shoots','shooting','shot']),
  ('hang',      ARRAY['hangs','hanging','hung']),
  ('sleep',     ARRAY['sleeps','sleeping','slept']),
  ('feed',      ARRAY['feeds','feeding','fed']),
  ('sweep',     ARRAY['sweeps','sweeping','swept']),
  ('weep',      ARRAY['weeps','weeping','wept']),
  ('bend',      ARRAY['bends','bending','bent']),
  ('lend',      ARRAY['lends','lending','lent']),
  ('bite',      ARRAY['bites','biting','bit','bitten']),
  ('hide',      ARRAY['hides','hiding','hid','hidden']),
  ('shake',     ARRAY['shakes','shaking','shook','shaken']),
  ('steal',     ARRAY['steals','stealing','stole','stolen']),
  ('freeze',    ARRAY['freezes','freezing','froze','frozen']),
  ('wake',      ARRAY['wakes','waking','woke','woken']),
  ('beat',      ARRAY['beats','beating','beaten']),
  ('blow',      ARRAY['blows','blowing','blew','blown']),
  ('cost',      ARRAY['costs','costing']),
  ('dig',       ARRAY['digs','digging','dug']),
  ('flee',      ARRAY['flees','fleeing','fled']),
  ('grind',     ARRAY['grinds','grinding','ground']),
  ('lay',       ARRAY['lays','laying','laid']),
  ('light',     ARRAY['lights','lighting','lit']),
  ('quit',      ARRAY['quits','quitting']),
  ('seek',      ARRAY['seeks','seeking','sought']),
  ('shine',     ARRAY['shines','shining','shone']),
  ('shrink',    ARRAY['shrinks','shrinking','shrank','shrunk']),
  ('slide',     ARRAY['slides','sliding','slid']),
  ('spin',      ARRAY['spins','spinning','spun']),
  ('split',     ARRAY['splits','splitting']),
  ('spread',    ARRAY['spreads','spreading']),
  ('spring',    ARRAY['springs','springing','sprang','sprung']),
  ('stick',     ARRAY['sticks','sticking','stuck']),
  ('sting',     ARRAY['stings','stinging','stung']),
  ('strike',    ARRAY['strikes','striking','struck']),
  ('swear',     ARRAY['swears','swearing','swore','sworn']),
  ('tear',      ARRAY['tears','tearing','tore','torn']),
  ('wind',      ARRAY['winds','winding','wound']),
  ('hurt',      ARRAY['hurts','hurting']),
  ('let',       ARRAY['lets','letting']),
  ('put',       ARRAY['puts','putting']),
  ('shut',      ARRAY['shuts','shutting']),
  ('cast',      ARRAY['casts','casting']),
  ('burst',     ARRAY['bursts','bursting']),
  ('swing',     ARRAY['swings','swinging','swung']),
  ('read',      ARRAY['reads','reading']),
  -- ── 불규칙 명사 복수 ──
  ('child',     ARRAY['children']),
  ('man',       ARRAY['men']),
  ('woman',     ARRAY['women']),
  ('person',    ARRAY['people','persons']),
  ('foot',      ARRAY['feet']),
  ('tooth',     ARRAY['teeth']),
  ('goose',     ARRAY['geese']),
  ('mouse',     ARRAY['mice']),
  ('ox',        ARRAY['oxen']),
  ('life',      ARRAY['lives']),
  ('knife',     ARRAY['knives']),
  ('wife',      ARRAY['wives']),
  ('leaf',      ARRAY['leaves']),
  ('half',      ARRAY['halves']),
  ('wolf',      ARRAY['wolves']),
  ('shelf',     ARRAY['shelves']),
  ('loaf',      ARRAY['loaves']),
  ('thief',     ARRAY['thieves']),
  ('calf',      ARRAY['calves']),
  ('self',      ARRAY['selves']),
  ('phenomenon',ARRAY['phenomena']),
  ('criterion', ARRAY['criteria']),
  ('datum',     ARRAY['data']),
  ('medium',    ARRAY['media']),
  ('analysis',  ARRAY['analyses']),
  ('basis',     ARRAY['bases']),
  ('crisis',    ARRAY['crises']),
  ('thesis',    ARRAY['theses']),
  ('bacterium', ARRAY['bacteria']),
  ('curriculum',ARRAY['curricula'])
)
UPDATE shared_dictionary d
SET inflected_forms = irr.forms
FROM irr
WHERE d.word = irr.lemma;
