-- supabase/migrations/20260906001200_drop_csat_dcp_inventory_superseded.sql
--
-- `csat_dcp_inventory()` 제거 — **이미 있던 집계표가 같은 일을 더 잘한다.**
--
-- ── 왜 만들었다가 지우나 (2026-09-06, 같은 날) ──────────────────────────────
-- 공정 ⑥(해설)의 눈금을 내려고 이 함수를 만들었다(20260905225559). 값은 맞았다 —
-- 직접 SQL 로 문항 656,984 · 해설 426,696 · 키/값 셈 불일치 0.
--
-- 그런데 **앱 경로로는 쓸 수 없었다.** supabase-js → PostgREST → 풀러로 부르면
-- statement_timeout 을 60초로 올려도 60,079ms 에서 취소된다(실측 2회). 직접 SQL 5.7초와
-- 10배 차이다 — **재는 자리가 다르면 수도 다르다.** 이 교훈을 하루에 두 번 배웠다
-- (ACP 롤업도 같은 이유로 다시 만들었다 — 20260906000100).
--
-- 그 처방으로 "matview 를 만들자" 고 적었는데, **이미 있었다**:
--   `textbook_shelf_inventory_mv` (20260831090000 · 30분마다 CONCURRENTLY 갱신)
--   읽기 RPC `textbook_shelf_inventory()` — 실측 **1.2초 · 136행 · 문항 656,984**
--
-- 같은 표를 같은 축(유형 × 수준)으로 집계하고, 해설 판정은 **더 엄격하다**:
--   우리 함수  `answer_key ? 'explanation_ko'`                             → 426,696
--   집계표     COALESCE(NULLIF(explanation_ko,''), NULLIF(rationale_ko,'')) → 427,831
-- 1,135건 차이이고 **저쪽이 옳다** — 키만 있고 값이 빈 문항을 「해설 있음」으로 세면
-- 구멍이 영영 안 보인다(그 migration 이 같은 이유를 이미 적어 두었다).
--
-- 남겨 두면 다음 사람이 "둘 중 뭘 써야 하나" 를 묻게 되고, 언젠가 둘이 다른 수를 말한다.
-- 쓰지 않는 집계 함수는 부채다.
--
-- ⚠️ 앱에서 이 함수를 부르는 곳은 **0** 이다(2026-09-06 grep 확인). 화면은 전부
--    `lib/csat/item-count.ts` 의 `loadDcpInventory()` 를 거치고, 그것이 집계표를 읽는다.
--    같은 파일의 `countItemCells()` 도 집계표로 갈아탔다 — 예전에는 칸마다 조회를 던져
--    화면마다 다른 수를 말할 수 있었다(실측: 설계 표와 현황판이 갈렸다).
--
-- 되돌리기: 20260905225559_csat_dcp_inventory.sql 을 다시 적용하면 된다. 데이터는 무관하다.

drop function if exists public.csat_dcp_inventory();
