// scripts/vcb/01b-ingest-ai-seed.ts
// VCB Method B — AI 시드 import: /vcb-seed-list 결과 JSONL 을
// vocab_sources (auto-insert, kind='ai_generated', tier='T1')
// + vocab_seed_candidates (seed_origin='ai_generated') 에 적재.
// Step 2/3 우회.
//
// 사용:
//   pnpm vcb:ingest-ai-seed --run-id <id> --seed-list <path>
//
// CLAUDE.md §19.4b 정합.
// 라이선스 안전망: DB 트리거 guard_ai_generated_license() 가 T1 강제.

import fs from 'node:fs';
import path from 'node:path';
import { parseArgs } from 'node:util';
import {
  getSupabaseAdmin,
  createLogger,
  IngestError,
  ValidationError,
  type SeedListItem,
  type Pos,
  type Cefr,
  type FrequencyTier,
} from '@vocaflow/vcb-core';

const log = createLogger({ script: '01b-ingest-ai-seed' });

interface IngestAiSeedOptions {
  runId: number;
  seedListPath: string;
}

const VALID_POS: ReadonlySet<Pos> = new Set([
  'NOUN',
  'VERB',
  'ADJ',
  'ADV',
  'PREP',
  'CONJ',
  'PRON',
  'DET',
  'INTJ',
]);
const VALID_CEFR: ReadonlySet<Cefr> = new Set([
  'A1',
  'A2',
  'B1',
  'B2',
  'C1',
  'C2',
]);
const VALID_TIER: ReadonlySet<FrequencyTier> = new Set([
  'core',
  'common',
  'moderate',
  'rare',
]);

function tierToCount(tier: FrequencyTier): number {
  switch (tier) {
    case 'core':
      return 4;
    case 'common':
      return 3;
    case 'moderate':
      return 2;
    case 'rare':
      return 1;
  }
}

function isSeedListItem(x: unknown): x is SeedListItem {
  if (typeof x !== 'object' || x === null) return false;
  const o = x as Record<string, unknown>;
  return (
    typeof o.lemma === 'string' &&
    o.lemma.length > 0 &&
    typeof o.pos === 'string' &&
    VALID_POS.has(o.pos as Pos) &&
    typeof o.cefr_estimate === 'string' &&
    VALID_CEFR.has(o.cefr_estimate as Cefr) &&
    typeof o.frequency_tier === 'string' &&
    VALID_TIER.has(o.frequency_tier as FrequencyTier) &&
    typeof o.rationale_short === 'string' &&
    typeof o.confidence === 'number' &&
    o.confidence >= 0 &&
    o.confidence <= 1
  );
}

function parseJsonl(content: string): SeedListItem[] {
  const lines = content.split('\n').filter((l) => l.trim().length > 0);
  const items: SeedListItem[] = [];

  lines.forEach((line, idx) => {
    let parsed: unknown;
    try {
      parsed = JSON.parse(line);
    } catch {
      throw new ValidationError('invalid JSON line', {
        line_number: idx + 1,
        line_preview: line.slice(0, 80),
      });
    }
    if (!isSeedListItem(parsed)) {
      throw new ValidationError('line does not match SeedListItem schema', {
        line_number: idx + 1,
      });
    }
    items.push(parsed);
  });

  return items;
}

function detectDuplicates(items: SeedListItem[]): string[] {
  const seen = new Map<string, number>();
  const dups: string[] = [];
  items.forEach((item) => {
    const key = `${item.lemma}|${item.pos}`;
    const count = (seen.get(key) ?? 0) + 1;
    seen.set(key, count);
    if (count === 2) dups.push(key);
  });
  return dups;
}

interface RunBasicRow {
  id: number;
  collection_slug: string;
  collection_title: string;
}

async function fetchRun(runId: number): Promise<RunBasicRow> {
  const sb = getSupabaseAdmin();
  const { data, error } = await sb
    .from('vocab_runs')
    .select('id, collection_slug, collection_title')
    .eq('id', runId)
    .single();

  if (error || !data) {
    throw new IngestError('run not found', {
      run_id: runId,
      error: error?.message,
    });
  }
  return data as RunBasicRow;
}

async function createAiSource(opts: {
  runId: number;
  collectionSlug: string;
  collectionTitle: string;
  seedListPath: string;
  specId: number | null;
  itemCount: number;
}): Promise<number> {
  const sb = getSupabaseAdmin();
  const ts = new Date().toISOString().replace(/[:.]/g, '-');
  const slug = `${opts.collectionSlug}-ai-seed-${ts}`;

  const citation = [
    'Generated via Vocaflow VCB seed-list command',
    opts.specId !== null ? `spec_id=${opts.specId}` : null,
    `run_id=${opts.runId}`,
    `count=${opts.itemCount}`,
    `file=${path.basename(opts.seedListPath)}`,
  ]
    .filter(Boolean)
    .join(', ');

  const { data, error } = await sb
    .from('vocab_sources')
    .insert({
      slug,
      title: `AI Generated Seed for ${opts.collectionTitle}`,
      kind: 'ai_generated',
      license_tier: 'T1',
      citation,
      url: null,
      language: 'en',
      notes: 'Auto-generated by VCB Method B',
    })
    .select('id')
    .single();

  if (error || !data) {
    throw new IngestError('ai_generated source insert failed', {
      slug,
      error: error?.message,
    });
  }
  return (data as { id: number }).id;
}

async function insertSeedCandidates(opts: {
  runId: number;
  items: SeedListItem[];
}): Promise<{ inserted: number; skipped: number }> {
  const sb = getSupabaseAdmin();

  const rows = opts.items.map((item, idx) => ({
    run_id: opts.runId,
    lemma: item.lemma,
    pos: item.pos,
    raw_count: tierToCount(item.frequency_tier),
    normalized_freq: null,
    rank_in_run: idx + 1,
    context_samples: [] as string[],
    seed_origin: 'ai_generated' as const,
  }));

  // ON CONFLICT (run_id, lemma, pos) DO NOTHING
  const { data, error } = await sb
    .from('vocab_seed_candidates')
    .upsert(rows, {
      onConflict: 'run_id,lemma,pos',
      ignoreDuplicates: true,
    })
    .select('id');

  if (error) {
    throw new IngestError('seed_candidates insert failed', {
      error: error.message,
    });
  }

  const inserted = data?.length ?? 0;
  return {
    inserted,
    skipped: rows.length - inserted,
  };
}

async function updateRunStatus(runId: number, status: string): Promise<void> {
  const sb = getSupabaseAdmin();
  const { error } = await sb
    .from('vocab_runs')
    .update({ status })
    .eq('id', runId);

  if (error) {
    throw new IngestError('run status update failed', {
      run_id: runId,
      error: error.message,
    });
  }
}

function extractSpecIdFromConfig(config: unknown): number | null {
  if (typeof config !== 'object' || config === null) return null;
  const c = config as Record<string, unknown>;
  if (typeof c.seed_spec_id === 'number') return c.seed_spec_id;
  return null;
}

async function run(opts: IngestAiSeedOptions): Promise<void> {
  const childLog = log.child({ run_id: opts.runId });
  childLog.info(
    { seed_list_path: opts.seedListPath },
    'ingest-ai-seed started'
  );

  if (!fs.existsSync(opts.seedListPath)) {
    throw new IngestError('seed list file not found', {
      path: opts.seedListPath,
    });
  }

  const content = fs.readFileSync(opts.seedListPath, 'utf8');
  if (content.charCodeAt(0) === 0xfeff) {
    throw new ValidationError(
      'seed list has UTF-8 BOM — must be without BOM',
      {
        path: opts.seedListPath,
      }
    );
  }
  if (content.includes('\r\n')) {
    throw new ValidationError(
      'seed list has CRLF line endings — must be LF only',
      {
        path: opts.seedListPath,
      }
    );
  }

  const items = parseJsonl(content);
  childLog.info({ count: items.length }, 'seed list parsed');

  const duplicates = detectDuplicates(items);
  if (duplicates.length > 0) {
    throw new ValidationError('duplicate (lemma, pos) detected', {
      duplicates: duplicates.slice(0, 10),
      total_duplicates: duplicates.length,
    });
  }

  const runRow = await fetchRun(opts.runId);

  // run config 에서 spec_id 추출 시도 (없으면 null)
  const sb = getSupabaseAdmin();
  const { data: runFull } = await sb
    .from('vocab_runs')
    .select('config')
    .eq('id', opts.runId)
    .single();
  const specId = extractSpecIdFromConfig(
    (runFull as { config?: unknown } | null)?.config
  );

  await updateRunStatus(opts.runId, 'ingesting');

  const sourceId = await createAiSource({
    runId: opts.runId,
    collectionSlug: runRow.collection_slug,
    collectionTitle: runRow.collection_title,
    seedListPath: opts.seedListPath,
    specId,
    itemCount: items.length,
  });

  childLog.info({ source_id: sourceId }, 'ai_generated source created');

  const { inserted, skipped } = await insertSeedCandidates({
    runId: opts.runId,
    items,
  });

  childLog.info(
    { inserted, skipped, total: items.length },
    'seed_candidates inserted'
  );

  // Step 2/3 우회 — 곧바로 looked_up 직전 상태 (extracted) 로
  await updateRunStatus(opts.runId, 'extracted');

  childLog.info('ingest-ai-seed completed');
}

function parseCliArgs(): IngestAiSeedOptions {
  const { values } = parseArgs({
    options: {
      'run-id': { type: 'string' },
      'seed-list': { type: 'string' },
    },
  });

  if (!values['run-id'] || !values['seed-list']) {
    throw new IngestError('--run-id and --seed-list are required');
  }

  return {
    runId: parseInt(values['run-id'], 10),
    seedListPath: path.resolve(values['seed-list']),
  };
}

const opts = parseCliArgs();
run(opts).catch((err) => {
  log.error(
    {
      err:
        err instanceof Error
          ? {
              name: err.name,
              message: err.message,
              code: (err as { code?: string }).code,
              context: (err as { context?: unknown }).context,
            }
          : err,
    },
    'ingest-ai-seed failed'
  );
  process.exit(1);
});
